// <auto-generated />
using ClassifiedAdvertising.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ClassifiedAdvertising.Data.Migrations
{
    [DbContext(typeof(ClassifiedAdvertisingDbContext))]
    [Migration("20170729071411_AddRoleAndAdvertisingEntities")]
    partial class AddRoleAndAdvertisingEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-preview2-25794")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClassifiedAdvertising.Data.Entities.Advertising", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("TypeAdvertisingId");

                    b.HasKey("Id");

                    b.HasIndex("TypeAdvertisingId");

                    b.ToTable("Advertisings");
                });

            modelBuilder.Entity("ClassifiedAdvertising.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ClassifiedAdvertising.Data.Entities.TypeAdvertising", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("TypeAdvertisings");
                });

            modelBuilder.Entity("ClassifiedAdvertising.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClassifiedAdvertising.Data.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("RoleId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("ClassifiedAdvertising.Data.Entities.Advertising", b =>
                {
                    b.HasOne("ClassifiedAdvertising.Data.Entities.TypeAdvertising", "TypeAdvertising")
                        .WithMany()
                        .HasForeignKey("TypeAdvertisingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClassifiedAdvertising.Data.Entities.UserRole", b =>
                {
                    b.HasOne("ClassifiedAdvertising.Data.Entities.Role")
                        .WithMany("Roles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
